// go generate gen.go
// Code generated by the command above; DO NOT EDIT.

package ipv4

import "vendor"

// Internet Control Message Protocol (ICMP) Parameters, Updated: 2018-02-26
const (
	ICMPTypeEchoReply              vendor.ICMPType = 0  // Echo Reply
	ICMPTypeDestinationUnreachable vendor.ICMPType = 3  // Destination Unreachable
	ICMPTypeRedirect               vendor.ICMPType = 5  // Redirect
	ICMPTypeEcho                   vendor.ICMPType = 8  // Echo
	ICMPTypeRouterAdvertisement    vendor.ICMPType = 9  // Router Advertisement
	ICMPTypeRouterSolicitation     vendor.ICMPType = 10 // Router Solicitation
	ICMPTypeTimeExceeded           vendor.ICMPType = 11 // Time Exceeded
	ICMPTypeParameterProblem       vendor.ICMPType = 12 // Parameter Problem
	ICMPTypeTimestamp              vendor.ICMPType = 13 // Timestamp
	ICMPTypeTimestampReply         vendor.ICMPType = 14 // Timestamp Reply
	ICMPTypePhoturis               vendor.ICMPType = 40 // Photuris
	ICMPTypeExtendedEchoRequest    vendor.ICMPType = 42 // Extended Echo Request
	ICMPTypeExtendedEchoReply      vendor.ICMPType = 43 // Extended Echo Reply
)

// Internet Control Message Protocol (ICMP) Parameters, Updated: 2018-02-26
var icmpTypes = map[vendor.ICMPType]string{
	0:  "echo reply",
	3:  "destination unreachable",
	5:  "redirect",
	8:  "echo",
	9:  "router advertisement",
	10: "router solicitation",
	11: "time exceeded",
	12: "parameter problem",
	13: "timestamp",
	14: "timestamp reply",
	40: "photuris",
	42: "extended echo request",
	43: "extended echo reply",
}
