// go generate gen.go
// Code generated by the command above; DO NOT EDIT.

package ipv6

import "vendor"

// Internet Control Message Protocol version 6 (ICMPv6) Parameters, Updated: 2018-03-09
const (
	ICMPTypeDestinationUnreachable                vendor.ICMPType = 1   // Destination Unreachable
	ICMPTypePacketTooBig                          vendor.ICMPType = 2   // Packet Too Big
	ICMPTypeTimeExceeded                          vendor.ICMPType = 3   // Time Exceeded
	ICMPTypeParameterProblem                      vendor.ICMPType = 4   // Parameter Problem
	ICMPTypeEchoRequest                           vendor.ICMPType = 128 // Echo Request
	ICMPTypeEchoReply                             vendor.ICMPType = 129 // Echo Reply
	ICMPTypeMulticastListenerQuery                vendor.ICMPType = 130 // Multicast Listener Query
	ICMPTypeMulticastListenerReport               vendor.ICMPType = 131 // Multicast Listener Report
	ICMPTypeMulticastListenerDone                 vendor.ICMPType = 132 // Multicast Listener Done
	ICMPTypeRouterSolicitation                    vendor.ICMPType = 133 // Router Solicitation
	ICMPTypeRouterAdvertisement                   vendor.ICMPType = 134 // Router Advertisement
	ICMPTypeNeighborSolicitation                  vendor.ICMPType = 135 // Neighbor Solicitation
	ICMPTypeNeighborAdvertisement                 vendor.ICMPType = 136 // Neighbor Advertisement
	ICMPTypeRedirect                              vendor.ICMPType = 137 // Redirect Message
	ICMPTypeRouterRenumbering                     vendor.ICMPType = 138 // Router Renumbering
	ICMPTypeNodeInformationQuery                  vendor.ICMPType = 139 // ICMP Node Information Query
	ICMPTypeNodeInformationResponse               vendor.ICMPType = 140 // ICMP Node Information Response
	ICMPTypeInverseNeighborDiscoverySolicitation  vendor.ICMPType = 141 // Inverse Neighbor Discovery Solicitation Message
	ICMPTypeInverseNeighborDiscoveryAdvertisement vendor.ICMPType = 142 // Inverse Neighbor Discovery Advertisement Message
	ICMPTypeVersion2MulticastListenerReport       vendor.ICMPType = 143 // Version 2 Multicast Listener Report
	ICMPTypeHomeAgentAddressDiscoveryRequest      vendor.ICMPType = 144 // Home Agent Address Discovery Request Message
	ICMPTypeHomeAgentAddressDiscoveryReply        vendor.ICMPType = 145 // Home Agent Address Discovery Reply Message
	ICMPTypeMobilePrefixSolicitation              vendor.ICMPType = 146 // Mobile Prefix Solicitation
	ICMPTypeMobilePrefixAdvertisement             vendor.ICMPType = 147 // Mobile Prefix Advertisement
	ICMPTypeCertificationPathSolicitation         vendor.ICMPType = 148 // Certification Path Solicitation Message
	ICMPTypeCertificationPathAdvertisement        vendor.ICMPType = 149 // Certification Path Advertisement Message
	ICMPTypeMulticastRouterAdvertisement          vendor.ICMPType = 151 // Multicast Router Advertisement
	ICMPTypeMulticastRouterSolicitation           vendor.ICMPType = 152 // Multicast Router Solicitation
	ICMPTypeMulticastRouterTermination            vendor.ICMPType = 153 // Multicast Router Termination
	ICMPTypeFMIPv6                                vendor.ICMPType = 154 // FMIPv6 Messages
	ICMPTypeRPLControl                            vendor.ICMPType = 155 // RPL Control Message
	ICMPTypeILNPv6LocatorUpdate                   vendor.ICMPType = 156 // ILNPv6 Locator Update Message
	ICMPTypeDuplicateAddressRequest               vendor.ICMPType = 157 // Duplicate Address Request
	ICMPTypeDuplicateAddressConfirmation          vendor.ICMPType = 158 // Duplicate Address Confirmation
	ICMPTypeMPLControl                            vendor.ICMPType = 159 // MPL Control Message
	ICMPTypeExtendedEchoRequest                   vendor.ICMPType = 160 // Extended Echo Request
	ICMPTypeExtendedEchoReply                     vendor.ICMPType = 161 // Extended Echo Reply
)

// Internet Control Message Protocol version 6 (ICMPv6) Parameters, Updated: 2018-03-09
var icmpTypes = map[vendor.ICMPType]string{
	1:   "destination unreachable",
	2:   "packet too big",
	3:   "time exceeded",
	4:   "parameter problem",
	128: "echo request",
	129: "echo reply",
	130: "multicast listener query",
	131: "multicast listener report",
	132: "multicast listener done",
	133: "router solicitation",
	134: "router advertisement",
	135: "neighbor solicitation",
	136: "neighbor advertisement",
	137: "redirect message",
	138: "router renumbering",
	139: "icmp node information query",
	140: "icmp node information response",
	141: "inverse neighbor discovery solicitation message",
	142: "inverse neighbor discovery advertisement message",
	143: "version 2 multicast listener report",
	144: "home agent address discovery request message",
	145: "home agent address discovery reply message",
	146: "mobile prefix solicitation",
	147: "mobile prefix advertisement",
	148: "certification path solicitation message",
	149: "certification path advertisement message",
	151: "multicast router advertisement",
	152: "multicast router solicitation",
	153: "multicast router termination",
	154: "fmipv6 messages",
	155: "rpl control message",
	156: "ilnpv6 locator update message",
	157: "duplicate address request",
	158: "duplicate address confirmation",
	159: "mpl control message",
	160: "extended echo request",
	161: "extended echo reply",
}
